sudo: false

language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgpgme11-dev

node_js:
 - "6"
 - "5"
 - "4"
 - "0.12"
 - "iojs"


install:
  - npm install

script:
  - npm test

notifications:
  email: false
   
