sudo: false

language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgpgme11-dev

node_js:
 - "5.0.x"
 - "4.4.x"
 - "4.3.x"
 - "4.2.x"
 - "4.1.x"
 - "4.0.x"
 - "0.12"

install:
  - npm install

script:
  - npm test

notifications:
  email: false
   
