sudo: false

language: node_js

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgpgme11-dev

node_js:
 - "6.0"
 - "5.0"
 - "4.4"
 - "4.3"
 - "4.2"
 - "4.1"
 - "4.0"
 - "0.12"

install:
  - npm install

script:
  - npm test

notifications:
  email: false
   
